version: '3.8'
services:
  auth-db:
    image: postgres:14
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:14
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    ports:
      - 8081:8081
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tu_password

  inventory-service:
    build: ./inventory-service
    ports:
      - 8082:8082
    depends_on:
      - inventory-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tu_password

  api-gateway:
    build: ./api-gateway
    ports:
      - 8080:8080
    depends_on:
      - auth-service
      - inventory-service

volumes:
  auth-db-data:
  inventory-db-data:
